"""add index

Revision ID: 1fe97f5ceaae
Revises: 09739a82733d
Create Date: 2026-07-16 12:50:28.436643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe97f5ceaae'
down_revision: Union[str, Sequence[str], None] = '09739a82733d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cities_latitude'), 'cities', ['latitude'], unique=False)
    op.create_index(op.f('ix_cities_longitude'), 'cities', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_longitude'), table_name='cities')
    op.drop_index(op.f('ix_cities_latitude'), table_name='cities')
    # ### end Alembic commands ###
