"""delete unique key

Revision ID: acf3d4a952d2
Revises: 1fe97f5ceaae
Create Date: 2026-07-17 10:41:57.617901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf3d4a952d2'
down_revision: Union[str, Sequence[str], None] = '1fe97f5ceaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=1)
    # ### end Alembic commands ###
